name: "Comprobar errores ortográficos y de formato Markdown"
on:
  push:
    paths:
      - "**/*.md"
      - "*.md"
      - assets/palabras.txt

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out fuentes
        uses: actions/checkout@v4
      - name: "Comprueba errores de formato Markdown"
        uses: articulate/actions-markdownlint@v1
      - uses: rojopolis/spellcheck-github-actions@v0
        name: "Comprueba ortografía"
        with:
          source_files: "README.md doc/persona-Jacinta.md doc/persona-currante.md doc/persona-encarni.md doc/user-journey-currante.md doc/user-journey-hr.md pull_request_template.md"
          task_name: Spellcheck
